### ISSUE TITLE
Port to a DotNetCore model for hosting flexibility

### ISSUE THREAD

**Issue by bikeoid** [hackgvl/trolley-tracker-api-dot-net#20]
Port code to use DotNetCore.   This would be a major rewrite, but would allow more hosting flexibility in the future.

**Comment by bikeoid** [comment]
Re: hosting option - if there were an possibility to host on Linux, what free / low cost Linux hosting option is available that wouldn't be CPU or bandwidth starved?

**Comment by jeremywight** [comment]
What level of access would we need? We can do shared VPS hosting
reasonably. If we need SSH access we could do a digital ocean box for
$10-20/month depending on resource needs.

**Comment by bikeoid** [comment]
Tentatively, I'd like to be able to log web and API accesses, as well as database transactions in addition to basic publish access.    Probably could get by without SSH.   I'll know more exactly after the port is complete.

**Comment by jeremywight** [comment]
👍

**Comment by jeremywight** [comment]
Add in the items from https://github.com/codeforgreenville/trolley-tracker-api-dot-net/issues/5

**Comment by dereckcurry** [comment]
Great meeting everyone tonight at the meetup. I'll start looking into this issue soon if it is ok with all. Thanks.

**Comment by bikeoid** [comment]
This model might be interesting to study - https://github.com/joewalling/mvc-core2-api-best-practices ;  there are no comments, but it's being developed month by month in the GSP Developers Group meeting; eventually there will be a React front end added.    The relevant part is the Inversion of Control (IOC) model ; applied to this project, all the logic will move out of the Controllers and into the Services layer so that testing will be possible.
