### ISSUE TITLE
Get trolley locations from Greenlink API

### ISSUE THREAD

**Issue by bikeoid** [hackgvl/trolley-tracker-api-dot-net#42]
Trolleys are now running dual beacons for location tracking.   Greenlink has requested that we obtain beacon information from their API so that they can eliminate the second cellular data plan from each trolley.

 Syncromatics RTPI API documentation is at https://syncromatics.docs.apiary.io/# .

**Comment by bikeoid** [comment]
This is now running on the dev server at http://yeahthattrolley.azurewebsites.net/DBVisualizer?ActiveFilter=1 ; Trolley colors will update to match the route as the driver logs in.

4 routes are displayed 24/7, but trolleys will be shown only while running.   Extra routes (Arts / Augusta) don't start running until May.

Need a way to migrate to production server and easily fall back to using original beacon if there is a problem while testing.

**Comment by bikeoid** [comment]
So on the first day of monitoring - Trolley 1702 (Heart of Main) stalled out on the development display at about 1:30 and never restarted for the rest of the day.   This also matched its position on the "Find Greenlink" app, so it wasn't problem with our Syncromatics interface layer.  1701 ran good for the afternoon.

At the close of the night, trolley 1701 was 'dancing' in jumps of about 40 meters between South Main street and Augusta St near that intersection.  Our beacon showed the trolley was actually about 300 meters away at the Greenlink depot down the street.  After the trolley headed back to Falls Park Drive, the Syncromatics interface finally started tracking the 1701 trolley again.  That type of error is very unusual for a GPS fix unless there is an interference signal near the antenna.  It didn't look like it was inside the building so I don't think that was the problem.

Our original beacons are still running as they should be and helped me confirm the nature of the problem!  I'll follow up with Greenlink.

**Comment by ajhodges** [comment]
Blows my mind that what is essentially a retrofitted student project running on a consumer grade cell phone could be more reliable than a profe$$ional solution... hope that is an outlier and not the norm!

**Comment by bikeoid** [comment]
This is now ready to go - switch between Beacons or Syncromatics via Database/Application Settings menu.  Will continue running existing beacons until reliability problem is solved.

**Comment by bikeoid** [comment]
Greenlink updated the routes to match the routes in Syncromatics.   The Combination route is used when one trolley is out of service.
I've switched the trolleys to use Syncromatics for now so that trolley colors match the route and they will show passenger load percentage.

**Comment by bikeoid** [comment]
Generally, the Syncromatics interface went well for Friday-Sunday.  A trolley was missing on Thursday night, but the original beacon wasn't reporting either , so I don't know what the issue was there.

There is a quirk regarding driver breaks - when the driver goes on break, the routing tablet is put on some sort of pause mode and they drive to a break location.   As soon as the tablet goes into pause mode, there is no more reporting.   So our system shows the trolley sitting at that position until it goes inactive after 5 minutes.   Then nothing until the driver re-activates the route on the tablet.   So there is no way to know when the trolley will show up at the first stop after break, or even that the trolley is on break.     And if the driver forgets to take the tablet out of pause, the trolley will be invisible as it resumes the route.   This actually happened where started on the route for a bit until I could ask the driver about the pause mode without distracting him.

Depending on the driver's actions, the passenger load may or may not be useful.  It is good at counting adults but may miss some children.    But a bigger problem is related to the pause mode; the system does not count entries / exits when in pause.   So if pause mode is selected when clearing the last stop before break, exiting passengers are not counted.    In our case we had 3 aboard, but it said we had 17 passengers because it wasn't counting departing passengers at the last stop.
