### ISSUE TITLE
Review route formatting

### ISSUE THREAD

**Issue by bikeoid** [hackgvl/trolley-tracker-api-dot-net#54]
@MarkMcDaniels , great work on the route formatting!   Please check the result on the Dev Server where I have 4 simulated routes to match what will be running this summer.  http://yeahthattrolley.azurewebsites.net/ClientWeb

Also, I noticed that the route schedule appears immediately - previously it came up only upon request or if there was nothing running.

I also moved the HTML formatting out of the code and into the web page where it belongs.  It should make future tuning much easier!

**Comment by MarkMcDaniels** [comment]
I'm currently out of town right now, and I'll try to take a look when I
have a few minutes.

On the instant pop-up, I'll look at that again. I didn't change any of the
outside code that generates the pop up. I added a touch of extra html, and
a top margin.

Sorry for a delay. I'm glad you liked what I made.

**Comment by MarkMcDaniels** [comment]
@bikeoid, Sorry, I'm still out of town, but I think a couple of changes, and it will be finished.

The popup automatic looks like I was using a different version of the index.html that didn't have the inline style in it. At id="schedules" it was supposed to look like this: 

`<div id="schedules" class="info-popup" style='display:none;'>`

(looks like I made that mistake, and you were right.)

For some reason the h6 for the route was rendering differently on my home machine, and should be changed to an h4 tag for the route name link. The links shouldn't have an underlines, and this should fix that:

.scheduleRoutes a {
     text-decoration: none;
}

I appreciate all the work you're putting in. Thank you.
